name: Deploy to Neocities (Mirror)

on:
  push:
    branches:
      - build

concurrency: # prevent concurrent deploys doing strange things
  group: deploy-to-neocities
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: lts/*

    - name: Create folder
      run: |
          mkdir -p public
          cp *.xml public/
          cp *.html public/
          cp -r note/ public/
          cp -r chan/ public/
          cp -r static/ public/
          cp -r pages/ public/
          ls public/


    - name: Deploy to neocities
      uses: bcomnes/deploy-to-neocities@v1
      with:
        api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
        cleanup: true
        dist_dir: public
