name: Deploy to Neocities (Mirror)

# only run on changes to master or when triggered manually
on:
  push:
    branches:
      - master
      
concurrency: # prevent concurrent deploys doing strange things
  group: deploy-to-neocities
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: lts/*
        
    - name: Create folder
      run: |
          mkdir -p public && cp *.html public/ && cp -r assets/ public/ && rm public/assets/js/list.ts && ls public/
          
    - name: Deploy to neocities
      uses: bcomnes/deploy-to-neocities@v1
      with:
        api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
        cleanup: true
        dist_dir: public
